db: "positions.db"
queries:
  - "{namespace=\"charge-crm\"}"
  - "{namespace=\"charger-prod\"}"
  - "{namespace=\"default\"}"
  - "{namespace=\"heatcrm\"}"
  - "{namespace=\"heating-prod\"}"  
  - "{namespace=\"iotgw\"}"
  - "{namespace=\"kubernetes-dashboard\"}"
  - "{namespace=\"payservice\"}"
loki-source: http://vpn.poersmart.com:3100
loki-destination: http://116.62.175.135:3100
show-sql: false